version: '2'

services:
    db:
        image: mysql:5.7.18
        container_name: symfony_db
        ports:
            - 33060:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: php7.1-fpm
        container_name: symfony_php
        volumes:
            - ${WORK_DIR_PATH}:/var/www/default
        environment:
            XDEBUG_ENABLE: ${XDEBUG_ENABLE}
    nginx:
        build: nginx
        container_name: symfony_nginx
        ports:
            - 800:80
        volumes:
            - ${WORK_DIR_PATH}:/var/www/default
